export default {
  AUTH_ID: import.meta.env.VITE_AUTH_ID,
  LOGIN_URL: import.meta.env.VITE_LOGIN_URL,
  REGISTER_URL: import.meta.env.VITE_VITE_REGISTER_URL,
  VITE_GET_ALL_RECIPES_URL: import.meta.env.VITE_VITE_VITE_GET_ALL_RECIPES_URL,
  VITE_GET_RECIPE_URL: import.meta.env.VITE_VITE_VITE_GET_RECIPE_URL,
  VITE_ADD_RECIPE_URL: import.meta.env.VITE_VITE_VITE_ADD_RECIPE_URL,
  VITE_UPDATE_RECIPE_URL: import.meta.env.VITE_VITE_VITE_UPDATE_RECIPE_URL,
  VITE_DELETE_RECIPE_URL: import.meta.env.VITE_VITE_VITE_DELETE_RECIPE_URL,
};
